title: Dante Calderón
email: dantehemerson@gmail.com
twitter_username: dantehemerson
github_username:  dantehemerson
description: Mi nombre es Dante Calderon y soy programador.

  # # Build settings
  # markdown: kramdown
  # plugins:
  #   - jekyll-feed


future: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  style: :compressed  # Change to :expanded for debugging


url: https://dantehemerson.github.io/

debug: false

permalink: /:title/


theme: minima

markdown: kramdown
highlighter: rouge


comments: true

plugins:
  - jekyll-paginate


## Pagination
paginate: 6
paginate_path: "/blog/page:num/"

